### ISSUE TITLE
AWS Inspector sync issue

### ISSUE THREAD

**Issue by T0mPh** [cartography-cncf/cartography#1025]
*Title*: *AWS Inspector sync issue*

*Description*:
> An unhandled exception is raised when cartography attempts to sync AWS Inspector in region ap-southeast-3

*To Reproduce*:
> I simply ran the following command
`cartography --neo4j-uri bolt://localhost:7687 --neo4j-password-prompt --neo4j-user neo4j`

*Logs*:
<pre>
INFO:cartography.intel.aws.inspector:Syncing AWS Inspector findings for account *redacted* and region ap-southeast-3
ERROR:cartography.sync:Unhandled exception during sync stage 'aws'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/botocore/httpsession.py", line 455, in send
    urllib_response = conn.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x7f4284d5dfc0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/cartography/sync.py", line 85, in run
    stage_func(neo4j_session, config)
  File "/usr/local/lib/python3.10/dist-packages/cartography/util.py", line 133, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/cartography/intel/aws/__init__.py", line 237, in start_aws_ingestion
    sync_successful = _sync_multiple_accounts(
  File "/usr/local/lib/python3.10/dist-packages/cartography/intel/aws/__init__.py", line 161, in _sync_multiple_accounts
    _sync_one_account(
  File "/usr/local/lib/python3.10/dist-packages/cartography/intel/aws/__init__.py", line 62, in _sync_one_account
    RESOURCE_FUNCTIONS[func_name](**sync_args)
  File "/usr/local/lib/python3.10/dist-packages/cartography/util.py", line 133, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/cartography/intel/aws/inspector.py", line 309, in sync
    findings = get_inspector_findings(boto3_session, region, current_aws_account_id)
  File "/usr/local/lib/python3.10/dist-packages/cartography/util.py", line 133, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/cartography/util.py", line 215, in inner_function
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/cartography/intel/aws/inspector.py", line 36, in get_inspector_findings
    members = aws_paginate(client, 'list_members', 'members')
  File "/usr/local/lib/python3.10/dist-packages/cartography/util.py", line 151, in aws_paginate
    for i, page in enumerate(paginator.paginate(**kwargs), start=1):
  File "/usr/local/lib/python3.10/dist-packages/botocore/paginate.py", line 269, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/botocore/paginate.py", line 357, in _make_request
    return self._method(**current_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/botocore/client.py", line 921, in _make_api_call
    http, parsed_response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/botocore/client.py", line 944, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python3.10/dist-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.10/dist-packages/botocore/endpoint.py", line 202, in _send_request
    while self._needs_retry(
  File "/usr/local/lib/python3.10/dist-packages/botocore/endpoint.py", line 354, in _needs_retry
    responses = self._event_emitter.emit(
  File "/usr/local/lib/python3.10/dist-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/botocore/retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
  File "/usr/local/lib/python3.10/dist-packages/botocore/retryhandler.py", line 284, in __call__
    should_retry = self._should_retry(
  File "/usr/local/lib/python3.10/dist-packages/botocore/retryhandler.py", line 320, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python3.10/dist-packages/botocore/retryhandler.py", line 363, in __call__
    checker_response = checker(
  File "/usr/local/lib/python3.10/dist-packages/botocore/retryhandler.py", line 247, in __call__
    return self._check_caught_exception(
  File "/usr/local/lib/python3.10/dist-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/usr/local/lib/python3.10/dist-packages/botocore/endpoint.py", line 281, in _do_get_response
    http_response = self._send(request)
  File "/usr/local/lib/python3.10/dist-packages/botocore/endpoint.py", line 377, in _send
    return self.http_session.send(request)
  File "/usr/local/lib/python3.10/dist-packages/botocore/httpsession.py", line 484, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://inspector2.ap-southeast-3.amazonaws.com/members/list"
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/botocore/httpsession.py", line 455, in send
    urllib_response = conn.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x7f4284d5dfc0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/cartography", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/cartography/cli.py", line 547, in main
    sys.exit(CLI(default_sync, prog='cartography').main(argv))
  File "/usr/local/lib/python3.10/dist-packages/cartography/cli.py", line 527, in main
    return cartography.sync.run_with_config(self.sync, config)
  File "/usr/local/lib/python3.10/dist-packages/cartography/sync.py", line 163, in run_with_config
    return sync.run(neo4j_driver, config)
  File "/usr/local/lib/python3.10/dist-packages/cartography/sync.py", line 85, in run
    stage_func(neo4j_session, config)
  File "/usr/local/lib/python3.10/dist-packages/cartography/util.py", line 133, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/cartography/intel/aws/__init__.py", line 237, in start_aws_ingestion
    sync_successful = _sync_multiple_accounts(
  File "/usr/local/lib/python3.10/dist-packages/cartography/intel/aws/__init__.py", line 161, in _sync_multiple_accounts
    _sync_one_account(
  File "/usr/local/lib/python3.10/dist-packages/cartography/intel/aws/__init__.py", line 62, in _sync_one_account
    RESOURCE_FUNCTIONS[func_name](**sync_args)
  File "/usr/local/lib/python3.10/dist-packages/cartography/util.py", line 133, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/cartography/intel/aws/inspector.py", line 309, in sync
    findings = get_inspector_findings(boto3_session, region, current_aws_account_id)
  File "/usr/local/lib/python3.10/dist-packages/cartography/util.py", line 133, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/cartography/util.py", line 215, in inner_function
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/cartography/intel/aws/inspector.py", line 36, in get_inspector_findings
    members = aws_paginate(client, 'list_members', 'members')
  File "/usr/local/lib/python3.10/dist-packages/cartography/util.py", line 151, in aws_paginate
    for i, page in enumerate(paginator.paginate(**kwargs), start=1):
  File "/usr/local/lib/python3.10/dist-packages/botocore/paginate.py", line 269, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/botocore/paginate.py", line 357, in _make_request
    return self._method(**current_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/botocore/client.py", line 921, in _make_api_call
    http, parsed_response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/botocore/client.py", line 944, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python3.10/dist-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.10/dist-packages/botocore/endpoint.py", line 202, in _send_request
    while self._needs_retry(
  File "/usr/local/lib/python3.10/dist-packages/botocore/endpoint.py", line 354, in _needs_retry
    responses = self._event_emitter.emit(
  File "/usr/local/lib/python3.10/dist-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/botocore/retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
  File "/usr/local/lib/python3.10/dist-packages/botocore/retryhandler.py", line 284, in __call__
    should_retry = self._should_retry(
  File "/usr/local/lib/python3.10/dist-packages/botocore/retryhandler.py", line 320, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python3.10/dist-packages/botocore/retryhandler.py", line 363, in __call__
    checker_response = checker(
  File "/usr/local/lib/python3.10/dist-packages/botocore/retryhandler.py", line 247, in __call__
    return self._check_caught_exception(
  File "/usr/local/lib/python3.10/dist-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/usr/local/lib/python3.10/dist-packages/botocore/endpoint.py", line 281, in _do_get_response
    http_response = self._send(request)
  File "/usr/local/lib/python3.10/dist-packages/botocore/endpoint.py", line 377, in _send
    return self.http_session.send(request)
  File "/usr/local/lib/python3.10/dist-packages/botocore/httpsession.py", line 484, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://inspector2.ap-southeast-3.amazonaws.com/members/list"
</pre>

*Additional info:*:
>  - Cartography version: [0.66.0rc2](https://github.com/lyft/cartography/releases/tag/0.66.0rc2). Previous versions raised an unhandled KeyError exception
>  - Python version: 3.10
>  - OS: Kali Linux

*Additional context*:
> The issue occurred when trying to scan an AWS environment. I have used the config and credentials files to store the access keys required. The cli is configured to use MFA.

Please let me know if I can provide any additional detail.

Regards,
Tom

**Comment by achantavy** [comment]
Thanks for filing this issue and providing all these details. We're having trouble with inspector too; am looking into it in detail.

If inspector data isn't important for you, to unblock your scans for now you can use the `--aws-requested-syncs` flag to specify all the datatypes you care about and simply not include inspector. See https://github.com/lyft/cartography/blob/7122301f65ffe328552631b1b93427c37d11b6e9/cartography/cli.py#L187-L195. 

Will see if I can get a repro going.

**Comment by T0mPh** [comment]
Hi @achantavy 
Thank you very much for your help! I'll proceed with the `--aws-requested-syncs` option. Please let me know if I can help in any way.

Regards,
Tom

**Comment by ramonpetgrave64** [comment]
related #988

**Comment by achantavy** [comment]
Hi @T0mPh, this issue is almost 3 years old haha -- sorry for not checking in sooner! Any chance you know if this is now resolved?

**Comment by jychp** [comment]
Fixed on https://github.com/cartography-cncf/cartography/pull/1341
