### ISSUE TITLE
@aws_handle_regions can swallow exceptions and cause get_* functions to return 0 items incorrectly

### ISSUE THREAD

**Issue by achantavy** [cartography-cncf/cartography#1398]
**Bug Template**

*Description*:
> What issue is being seen?  Describe what should be happening instead of the bug, for example: Cartography should not crash, the expected value isn't returned, the data schema is wrong, etc.

This is a bad one.

*To Reproduce*:
> Steps to reproduce the behavior.  Provide all data and inputs required to reproduce the issue.

1. Create a resource policy on a dynamodb table that denies the describe-dynamodb-table action.
2. Run the cartography sync.

*Logs*:
> If applicable, copy and paste your console log with the failing stack trace.

**Expected behavior: **

cartography should either 
- (best effort approach) skip over the dynamodbtable that it is unable to describe, log a warning message, continue enumerating the other tables, and return the data that it was able to retrieve
- (all or nothing strict fail approach) or it should raise an exception

**Actual behavior:**

cartography writes a warning message, swallows the exception, and returns 0 items in the list.

```
Python 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto3
>>> b3session = boto3.Session(profile_name='profile')
>>> from cartography.intel.aws.dynamodb import get_dynamodb_tables
>>> tables = get_dynamodb_tables(b3session, 'us-east-1')
User: arn:aws:sts::account:assumed-role/read-only/botocore-session-1733519864 is not authorized to perform: dynamodb:DescribeTable on resource: arn:aws:dynamodb:us-east-1:account:table/sample-datastores-production-dynamo-table with an explicit deny in a resource-based policy in this region. Skipping...
>>> len(tables)
0
```

This is dangerous because it's very difficult to trace why the graph incorrectly returned 0 items, and this affects all functions that are decorated with `@aws_handle_regions`.

*Please complete the following information:*:
>  - Cartography release version or commit hash [e.g. 0.12.0 or 95e8e11913e2a44a4d4682506d8364a638ceac69]
0.95.0

**Comment by ramonpetgrave64** [comment]
We will need to debug, but I suspect the unreturned error should be AccessDenied. think maybe the call to describe each table needs to be moved out and done in a separate function. This way the listing function should return as normal, but each of the describe_table calls may have their own individual error. 
https://github.com/cartography-cncf/cartography/blob/7feb2185ebdabdd14cce97c736226793a880e6e3/cartography/intel/aws/dynamodb.py#L25

example:

```
@aws_handle_regions
def list_dynamodb_tables(…)
    …

@aws_handle_regions
def describe_dynamodb_tables(table_names, .)
    …

tables_names = list_dynamodb_tables(…)
tables = describe_dynamodb_tables(table_names, .)
```

btw this might be a good candidate for concurrency. 
https://github.com/cartography-cncf/cartography/blob/7feb2185ebdabdd14cce97c736226793a880e6e3/cartography/intel/aws/ecr.py#L159

**Comment by pvasilevich** [comment]
We have the following problem. In some accounts we have few regions disabled and while scanning for EC2 launch templates Cartography is getting 0 items, but code itself expects non-empty result. I assume the root cause is the same.

```
INFO:cartography.intel.aws.ec2.launch_templates:Syncing launch templates for region 'af-south-1' in account 'xxxxxxx'.
WARNING:cartography.util:AWS was not able to validate the provided access credentials in this region. Skipping...
ERROR:cartography.sync:Unhandled exception during sync stage 'aws'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/cartography/sync.py", line 113, in run
    stage_func(neo4j_session, config)
  File "/usr/local/lib/python3.10/site-packages/cartography/util.py", line 194, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/cartography/intel/aws/__init__.py", line 298, in start_aws_ingestion
    sync_successful = _sync_multiple_accounts(
  File "/usr/local/lib/python3.10/site-packages/cartography/intel/aws/__init__.py", line 169, in _sync_multiple_accounts
    _sync_one_account(
  File "/usr/local/lib/python3.10/site-packages/cartography/intel/aws/__init__.py", line 64, in _sync_one_account
    RESOURCE_FUNCTIONS[func_name](**sync_args)
  File "/usr/local/lib/python3.10/site-packages/cartography/util.py", line 194, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/cartography/intel/aws/ec2/launch_templates.py", line 156, in sync_ec2_launch_templates
    templates, versions = get_launch_templates(boto3_session, region)
ValueError: not enough values to unpack (expected 2, got 0)
```

We are using Cartography 0.98. Previously we were using 0.92 and there were no such error.

**Comment by achantavy** [comment]
@pvasilevich - Thanks for the stack trace, will be able to look in a couple hours

**Comment by achantavy** [comment]
@pvasilevich should be fixed now that https://github.com/cartography-cncf/cartography/issues/1481 is merged. Once the 0.100.0rc4 image is done building (should be in a couple minutes), you can give it a try

**Comment by pvasilevich** [comment]
Yes, I can confirm that 0.100.0 image fixes this problem for me. Thank you.
