### ISSUE TITLE
AWS sso:ListPermissionSets crashes on child accounts with AccessDeniedException

### ISSUE THREAD

**Issue by achantavy** [cartography-cncf/cartography#1415]
*Description*:
> What issue is being seen?  Describe what should be happening instead of the bug, for example: Cartography should not crash, the expected value isn't returned, the data schema is wrong, etc.

The cartography sync crashes with an AccessDeniedException when an account that does not have identitycenter configured attempts to run sso:ListPermissionSets. This happens even when the role running cartography is explicitly allowed to listpermissionsets.

*To Reproduce*:
> Steps to reproduce the behavior.  Provide all data and inputs required to reproduce the issue.

1. Configure an AWS organization with more than 1 child account. 
2. Set up identitycenter on the main aws account.
3. Run the cartography sync.

Expected behavior: the cartography sync will show that the identitycenter is attached to the main account and correctly list permissionsets on that main account. When it syncs the child accounts, it should gracefully continue when it encounters the access denied exception.

Actual behavior: the cartography sync crashes. It seems like a weird quirk of AWS to throw an accessdeniedexception here when the identitycenter doesn't exist on this child account.

*Logs*:
> If applicable, copy and paste your console log with the failing stack trace.

```
botocore.errorfactory.AccessDeniedException: An error occurred (AccessDeniedException) when calling the ListPermissionSets operation: User: arn:aws:sts::ACCOUNT1:assumed-role/cartography-read-only/botocore-session-1734851166 is not authorized to perform: sso:ListPermissionSets
ERROR:cartography.intel.aws:AWS sync failed for accounts ['ACCOUNT2', 'ACCOUNT1']
ERROR:cartography.sync:Unhandled exception during sync stage 'aws'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/cartography/sync.py", line 113, in run
    stage_func(neo4j_session, config)
  File "/usr/local/lib/python3.10/site-packages/cartography/util.py", line 198, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/cartography/intel/aws/__init__.py", line 298, in start_aws_ingestion
    sync_successful = _sync_multiple_accounts(
  File "/usr/local/lib/python3.10/site-packages/cartography/intel/aws/__init__.py", line 196, in _sync_multiple_accounts
    raise Exception('\n'.join(exception_tracebacks))
Exception: 2024-12-22 07:06:06.043570 - Exception for account ID: ACCOUNT2
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/cartography/intel/aws/__init__.py", line 169, in _sync_multiple_accounts
    _sync_one_account(
  File "/usr/local/lib/python3.10/site-packages/cartography/intel/aws/__init__.py", line 64, in _sync_one_account
    RESOURCE_FUNCTIONS[func_name](**sync_args)
  File "/usr/local/lib/python3.10/site-packages/cartography/util.py", line 198, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/cartography/intel/aws/identitycenter.py", line 273, in sync_identity_center_instances
    permission_sets = get_permission_sets(boto3_session, instance_arn, region)
  File "/usr/local/lib/python3.10/site-packages/cartography/util.py", line 198, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/cartography/intel/aws/identitycenter.py", line 67, in get_permission_sets
    for page in paginator.paginate(InstanceArn=instance_arn):
  File "/usr/local/lib/python3.10/site-packages/botocore/paginate.py", line 269, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/paginate.py", line 357, in _make_request
    return self._method(**current_kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.AccessDeniedException: An error occurred (AccessDeniedException) when calling the ListPermissionSets operation: User: arn:aws:sts::ACCOUNT2:assumed-role/cartography-read-only/botocore-session-1734850578 is not authorized to perform: sso:ListPermissionSets
```

*Screenshots*:
> If applicable, add screenshots to help explain your problem.

*Please complete the following information:*:
>  - Cartography release version or commit hash [e.g. 0.12.0 or 95e8e11913e2a44a4d4682506d8364a638ceac69]
0.96.2

**Comment by achantavy** [comment]
cc: @SecPrez - i think we were talking about this briefly a couple weeks ago
