### ISSUE TITLE
Failure during the cleanup job of EC2 snapshots

### ISSUE THREAD

**Issue by marco-lancini** [cartography-cncf/cartography#665]
I've experienced a new failure during the cleanup job of EC2 snapshots:

```
neobolt.exceptions.ClientError: Unable to load NODE with id <redacted>.
```

Full log:

```


ERROR:cartography.graph.job:Unhandled error while executing statement in job 'cleanup EBS Snapshots': Unable to load NODE with id <redacted>.
ERROR:cartography.sync:Unhandled exception during sync stage 'aws'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/cartography/sync.py", line 73, in run
    stage_func(neo4j_session, config)
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 66, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/__init__.py", line 202, in start_aws_ingestion
    _sync_multiple_accounts(
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/__init__.py", line 139, in _sync_multiple_accounts
    _sync_one_account(
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/__init__.py", line 57, in _sync_one_account
    RESOURCE_FUNCTIONS[func_name](**sync_args)
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 66, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/ec2/snapshots.py", line 117, in sync_ebs_snapshots
    cleanup_snapshots(neo4j_session, common_job_parameters)
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 66, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/ec2/snapshots.py", line 99, in cleanup_snapshots
    run_cleanup_job(
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 32, in run_cleanup_job
    GraphJob.run_from_json(
  File "/usr/local/lib/python3.9/site-packages/cartography/graph/job.py", line 95, in run_from_json
    job.run(neo4j_session)
  File "/usr/local/lib/python3.9/site-packages/cartography/graph/job.py", line 45, in run
    stm.run(neo4j_session)
  File "/usr/local/lib/python3.9/site-packages/cartography/graph/statement.py", line 48, in run
    tx: neo4j.Transaction = session.begin_transaction()
  File "/usr/local/lib/python3.9/site-packages/neo4j/__init__.py", line 614, in begin_transaction
    self._open_transaction(metadata=metadata, timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/neo4j/__init__.py", line 619, in _open_transaction
    self._connect(access_mode)
  File "/usr/local/lib/python3.9/site-packages/neo4j/__init__.py", line 381, in _connect
    self._connection.sync()
  File "/usr/local/lib/python3.9/site-packages/neobolt/direct.py", line 527, in sync
    detail_delta, summary_delta = self.fetch()
  File "/usr/local/lib/python3.9/site-packages/neobolt/direct.py", line 419, in fetch
    return self._fetch()
  File "/usr/local/lib/python3.9/site-packages/neobolt/direct.py", line 461, in _fetch
    response.on_failure(summary_metadata or {})
  File "/usr/local/lib/python3.9/site-packages/neobolt/direct.py", line 755, in on_failure
    raise CypherError.hydrate(**metadata)
neobolt.exceptions.ClientError: Unable to load NODE with id <redacted>.
Traceback (most recent call last):
  File "/usr/local/bin/cartography", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/cartography/cli.py", line 441, in main
    return CLI(default_sync, prog='cartography').main(argv)
  File "/usr/local/lib/python3.9/site-packages/cartography/cli.py", line 421, in main
    return cartography.sync.run_with_config(self.sync, config)
  File "/usr/local/lib/python3.9/site-packages/cartography/sync.py", line 150, in run_with_config
    return sync.run(neo4j_driver, config)
  File "/usr/local/lib/python3.9/site-packages/cartography/sync.py", line 73, in run
    stage_func(neo4j_session, config)
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 66, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/__init__.py", line 202, in start_aws_ingestion
    _sync_multiple_accounts(
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/__init__.py", line 139, in _sync_multiple_accounts
    _sync_one_account(
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/__init__.py", line 57, in _sync_one_account
    RESOURCE_FUNCTIONS[func_name](**sync_args)
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 66, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/ec2/snapshots.py", line 117, in sync_ebs_snapshots
    cleanup_snapshots(neo4j_session, common_job_parameters)
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 66, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/ec2/snapshots.py", line 99, in cleanup_snapshots
    run_cleanup_job(
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 32, in run_cleanup_job
    GraphJob.run_from_json(
  File "/usr/local/lib/python3.9/site-packages/cartography/graph/job.py", line 95, in run_from_json
    job.run(neo4j_session)
  File "/usr/local/lib/python3.9/site-packages/cartography/graph/job.py", line 45, in run
    stm.run(neo4j_session)
  File "/usr/local/lib/python3.9/site-packages/cartography/graph/statement.py", line 48, in run
    tx: neo4j.Transaction = session.begin_transaction()
  File "/usr/local/lib/python3.9/site-packages/neo4j/__init__.py", line 614, in begin_transaction
    self._open_transaction(metadata=metadata, timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/neo4j/__init__.py", line 619, in _open_transaction
    self._connect(access_mode)
  File "/usr/local/lib/python3.9/site-packages/neo4j/__init__.py", line 381, in _connect
    self._connection.sync()
  File "/usr/local/lib/python3.9/site-packages/neobolt/direct.py", line 527, in sync
    detail_delta, summary_delta = self.fetch()
  File "/usr/local/lib/python3.9/site-packages/neobolt/direct.py", line 419, in fetch
    return self._fetch()
  File "/usr/local/lib/python3.9/site-packages/neobolt/direct.py", line 461, in _fetch
    response.on_failure(summary_metadata or {})
  File "/usr/local/lib/python3.9/site-packages/neobolt/direct.py", line 755, in on_failure
    raise CypherError.hydrate(**metadata)
neobolt.exceptions.ClientError: Unable to load NODE with id <redacted>.
```

**Comment by marco-lancini** [comment]
CC: @achantavy

**Comment by achantavy** [comment]
@marco-lancini: This feels like a DB provisioned with not enough resources - it might be worth asking Neo4j community forums if this comes up again. @mpurusottamc have you seen something like this before?

---

Otherwise if this is due to bad code, we could improve by employing the approach described here: https://github.com/lyft/cartography/issues/522#issuecomment-885402304

Specifically, we could do something like

```python
def perform_db_action(session: Session, data_list: List[Dict[str, Optional[str]]], update_tag: int) -> None:
    session.write_transaction(_tx_function, data_list, update_tag)

@timeit
def _tx_function(tx: neo4j.Transaction, data_list: List[Dict], update_tag: int) -> None:
    query = """
        neo4j query goes here
    """
    tx.run(query, Data=data_list, UpdateTag=update_tag)
```

The `write_transaction` function gives us built-in retries on failures like this.

**Comment by marco-lancini** [comment]
> This feels like a DB provisioned with not enough resources

The reason why I don't think it is purely Neo4j related is that the error is consistent for the same resource every time I try to run it

**Comment by achantavy** [comment]
Reopening while we test e2e to verify.

**Comment by achantavy** [comment]
Fix here: https://github.com/cartography-cncf/cartography/pull/1623
