### ISSUE TITLE
Unhandled IllegalLocationConstraintException in s3

### ISSUE THREAD

**Issue by krisek** [cartography-cncf/cartography#842]
*Title*: *Unhandled IllegalLocationConstraintException in s3*

*Description*:
> Sync process crashing with

```
cartography-loader-adhoc--1-9gbxc cartography ERROR:cartography.sync:Unhandled exception during sync stage 'aws'                                                                      
cartography-loader-adhoc--1-9gbxc cartography Traceback (most recent call last):                                                                                                      
cartography-loader-adhoc--1-9gbxc cartography   File "/usr/local/lib/python3.10/site-packages/cartography/sync.py", line 74, in run                                                   
cartography-loader-adhoc--1-9gbxc cartography     stage_func(neo4j_session, config)                                                                                                   
cartography-loader-adhoc--1-9gbxc cartography   File "/usr/local/lib/python3.10/site-packages/cartography/util.py", line 117, in timed                                                
cartography-loader-adhoc--1-9gbxc cartography     return method(*args, **kwargs)                                                                                                      
cartography-loader-adhoc--1-9gbxc cartography   File "/usr/local/lib/python3.10/site-packages/cartography/intel/aws/__init__.py", line 220, in start_aws_ingestion                    
cartography-loader-adhoc--1-9gbxc cartography     _sync_multiple_accounts(                                                                                                            
cartography-loader-adhoc--1-9gbxc cartography   File "/usr/local/lib/python3.10/site-packages/cartography/intel/aws/__init__.py", line 157, in _sync_multiple_accounts                
cartography-loader-adhoc--1-9gbxc cartography     _sync_one_account(                                                                                                                  
cartography-loader-adhoc--1-9gbxc cartography   File "/usr/local/lib/python3.10/site-packages/cartography/intel/aws/__init__.py", line 60, in _sync_one_account                       
cartography-loader-adhoc--1-9gbxc cartography     RESOURCE_FUNCTIONS[func_name](**sync_args)                                                                                          
cartography-loader-adhoc--1-9gbxc cartography   File "/usr/local/lib/python3.10/site-packages/cartography/util.py", line 117, in timed                                                
cartography-loader-adhoc--1-9gbxc cartography     return method(*args, **kwargs)                                                                                                      
cartography-loader-adhoc--1-9gbxc cartography   File "/usr/local/lib/python3.10/site-packages/cartography/intel/aws/s3.py", line 649, in sync                                         
cartography-loader-adhoc--1-9gbxc cartography     load_s3_details(neo4j_session, acl_and_policy_data_iter, current_aws_account_id, update_tag)                                        
cartography-loader-adhoc--1-9gbxc cartography   File "/usr/local/lib/python3.10/site-packages/cartography/util.py", line 117, in timed                                                
cartography-loader-adhoc--1-9gbxc cartography     return method(*args, **kwargs)                                                                                                      
cartography-loader-adhoc--1-9gbxc cartography   File "/usr/local/lib/python3.10/site-packages/cartography/intel/aws/s3.py", line 359, in load_s3_details                              
cartography-loader-adhoc--1-9gbxc cartography     for bucket, acl, policy, encryption, versioning, public_access_block in s3_details_iter:                                            
cartography-loader-adhoc--1-9gbxc cartography   File "/usr/local/lib/python3.10/site-packages/cartography/intel/aws/s3.py", line 66, in get_s3_bucket_details                         
cartography-loader-adhoc--1-9gbxc cartography     acl = get_acl(bucket, client)                                                                                                       
cartography-loader-adhoc--1-9gbxc cartography   File "/usr/local/lib/python3.10/site-packages/cartography/util.py", line 117, in timed                                                
cartography-loader-adhoc--1-9gbxc cartography     return method(*args, **kwargs)                                                                                                      
cartography-loader-adhoc--1-9gbxc cartography   File "/usr/local/lib/python3.10/site-packages/cartography/intel/aws/s3.py", line 101, in get_acl                                      
cartography-loader-adhoc--1-9gbxc cartography     acl = client.get_bucket_acl(Bucket=bucket['Name'])                                                                                  
cartography-loader-adhoc--1-9gbxc cartography   File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 508, in _api_call
cartography-loader-adhoc--1-9gbxc cartography     return self._make_api_call(operation_name, kwargs)
cartography-loader-adhoc--1-9gbxc cartography   File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 911, in _make_api_call
cartography-loader-adhoc--1-9gbxc cartography     raise error_class(parsed_response, operation_name)
```

*To Reproduce*:
> Start a sync on an account that triggers the issue.

*Please complete the following information:*:
>  - cryptography==3.3.2
>  - Python 3.10
>  - Alpine

**Comment by ramonpetgrave64** [comment]
Can you tell us if there's something special about the particular bucket that caused the error. Depending on the situation, we may want to add this `IllegalLocationConstraintException` exception to `_is_common_exception()`.

**Comment by krisek** [comment]
I think the admin of the given AWS account created a broken bucket, I submitted in the meanwhile the patch to fix in place, but you are right maybe it makes sense to add as a common exception. On the other hand... I sync a large estate, the sync process takes hours, so it is super annoying if any exception breaks it in the middle :)
